
import { Language, TranslationStrings, Category } from './types';

export const UI_STRINGS: Record<Language, TranslationStrings> = {
  [Language.HE]: {
    appName: 'Sabor & Masoret',
    addRecipe: 'הוספת מתכון חדש',
    title: 'שם המתכון',
    description: 'תיאור קצר',
    ingredients: 'מצרכים',
    instructions: 'אופן ההכנה',
    notes: 'הערות',
    oven: 'הוראות חימום בתנור',
    save: 'שמור מתכון',
    cancel: 'ביטול',
    generateImage: 'צור תמונה ב-AI',
    uploadImage: 'העלה תמונה',
    promptPlaceholder: 'תאר את המנה כדי ליצור תמונה...',
    bonAppetit: 'בתאבון!',
    exportPdf: 'ייצוא ל-PDF',
    category: 'קטגוריה',
    amount: 'כמות',
    unit: 'יחידה',
    addIngredient: 'הוסף מצרך',
    addStep: 'הוסף שלב',
    translateLoading: 'מתרגם את המתכון...',
    noRecipes: 'אין עדיין מתכונים. הגיע הזמן לבשל!',
    imageDescription: 'תיאור לתמונה',
    ingredientCategories: ['כללי', 'ירקות', 'בשר', 'חלבי', 'תבלינים', 'מאפים'],
    importFromUrl: 'ייבוא מכתובת URL',
    urlPlaceholder: 'הדבק כאן כתובת אתר עם מתכון...',
    importing: 'מייבא מתכון...',
    importError: 'שגיאה בייבוא המתכון. וודא שהכתובת תקינה.',
    manageCategories: 'ניהול קטגוריות',
    categoryNameHe: 'שם קטגוריה (עברית)',
    categoryNameEs: 'שם קטגוריה (ספרדית)',
    allCategories: 'הכל',
    uncategorized: 'ללא קטגוריה'
  },
  [Language.ES]: {
    appName: 'Sabor & Masoret',
    addRecipe: 'Nueva Receta',
    title: 'Nombre de la receta',
    description: 'Breve descripción',
    ingredients: 'Ingredientes',
    instructions: 'Preparación',
    notes: 'Notas',
    oven: 'Instrucciones de horno',
    save: 'Guardar receta',
    cancel: 'Cancelar',
    generateImage: 'Crear imagen con IA',
    uploadImage: 'Subir imagen',
    promptPlaceholder: 'Describe el plato para crear una imagen...',
    bonAppetit: '¡Buen provecho!',
    exportPdf: 'Exportar a PDF',
    category: 'Categoría',
    amount: 'Cantidad',
    unit: 'Unidad',
    addIngredient: 'Añadir ingrediente',
    addStep: 'Añadir paso',
    translateLoading: 'Traduciendo receta...',
    noRecipes: 'No hay recetas aún. ¡A cocinar!',
    imageDescription: 'Descripción de imagen',
    ingredientCategories: ['General', 'Verduras', 'Carne', 'Lácteos', 'Especias', 'Panadería'],
    importFromUrl: 'Importar desde URL',
    urlPlaceholder: 'Pega aquí la URL de una receta...',
    importing: 'Importando receta...',
    importError: 'Error al importar. Verifica que la URL sea válida.',
    manageCategories: 'Gestionar Categorías',
    categoryNameHe: 'Nombre (Hebreo)',
    categoryNameEs: 'Nombre (Español)',
    allCategories: 'Todo',
    uncategorized: 'Sin categoría'
  }
};

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'cat-desserts', [Language.HE]: 'קינוחים', [Language.ES]: 'Postres' },
  { id: 'cat-main', [Language.HE]: 'מנות עיקריות', [Language.ES]: 'Platos Principales' },
  { id: 'cat-bakery', [Language.HE]: 'מאפים', [Language.ES]: 'Panadería' },
  { id: 'cat-salads', [Language.HE]: 'סלטים', [Language.ES]: 'Ensaladas' },
];

export const UNITS: Record<string, Record<Language, string>> = {
  gram: { [Language.HE]: 'גרם', [Language.ES]: 'gramos' },
  kg: { [Language.HE]: 'ק"ג', [Language.ES]: 'kg' },
  tsp: { [Language.HE]: 'כפית', [Language.ES]: 'cdta' },
  tbsp: { [Language.HE]: 'כף', [Language.ES]: 'cda' },
  cup: { [Language.HE]: 'כוס', [Language.ES]: 'taza' },
  pinch: { [Language.HE]: 'קורט', [Language.ES]: 'pizca' },
  drizzle: { [Language.HE]: 'זילוף', [Language.ES]: 'chorrito' },
  units: { [Language.HE]: 'יחידות', [Language.ES]: 'unidades' },
  ml: { [Language.HE]: 'מ"ל', [Language.ES]: 'ml' },
  liters: { [Language.HE]: 'ליטר', [Language.ES]: 'litros' },
};
